version: "3.0"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tp3-web
    volumes:
     - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - bd
    links:
      - bd
  
  bd:
    container_name: tp3-bd
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: equipe6
    volumes:
      - ./src:/docker-entrypoint-initdb.d