version: '3'
networks:
  mynetwork:
services:
  apache:
    container_name: tp3-web
    image: php:8.2-apache
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - bd
    command: >
      bash -c "
        docker-php-ext-install mysqli
        apache2-foreground
      "
    links:
      - bd
    networks:
      - mynetwork
  bd:
    container_name: tp3-bd
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=equipe6
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./src/:/docker-entrypoint-initdb.d/
    networks:
      - mynetwork

